[programs.localnet]
solana_todo = "HLEa26jhsW2qVg7zeR67jzLWTcYZWWhBa5nVZK6pxCBM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/cloudyun/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
